name: Build

on: push

jobs:

  android:

    runs-on: windows-latest

    steps:
      - name: Set up NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: 'latest'

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Print environment
        run: |
          nuget help
          msbuild -version

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build app
        run: |
          nuget restore
          msbuild ./src/Android/Android.csproj /p:Configuration=Debug

  ios:

    runs-on: macos-latest

    steps:
      - name: Print environment
        run: |
          nuget help
          msbuild -version

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build app
        run: |
          nuget restore
          msbuild /verbosity:normal /p:Platform=iPhone /p:Configuration=Debug
